language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: chalice deploy
notifications:
  slack:
    on_success: always
    on_failure: change
    template:
    - "%{build_url}"
    - "%{commit_message}"
    - 'Change view: %{compare_url}'
    rooms:
      secure: IEHFKgwDNGcAXb+nTQpuQ7762T/DSNniOSqmGTphRuUDa7BMTWL32wnBfx5C0KZZfL9/CNg6Qt2n0/NdzcdAnPtvt4eyURnZ3NYmMIo5Cw2h4sZA7mRYPddKZfvv+oNkbIpfBHNGRdYSBvWgZfnX055N8aQn0JXy5s5tg+Efj+OiLcN+5hrbMy8DSoA0nPpNrr28hY9pzilufK07U9FF+BCrv7jAoKI0xDWj8x21myKN5lMxZZPI9GVvmNV9oXlJTWCioM2CbymrFG5itOjCbJP40UbmkxO9L1rcWiuPulJ1ixBd0ZpDXP4vd6nryt9zJ92axYS0Q3yMC6iOkGd80FKOnEjTGsMPPDelgUXwovx0+31Of3N6Puf3JPhV8aQluf2wdyN83GXnYbmQPKpIWDWYJCpv5pNG4ryaOF4/ALLPRJ8E2+kz62zM+VerH7/hO1ZDLWQcVHkjjmK0BZ7dlH1jIUmy1YGq1coUS8n9vUirXGVQoEojpcj3vv3Z5yGOdnFHNWZD8EkBAJNPhrPXJB5vV/0re9ehiheVtU9N+8Vb0xGc5BLnIuAxkIN5ImiC43ZoSEfP0Tk/kra9inuz32Rc8+ijm/Pb73hw4uv+4O/5MIQbFax/mDK/o01MzmskBzVYCA9ecQAoVYSgLboXQGg4tcfMmlyikqNJvObSgxc=
env:
  secure: dXELbxr31Mn4AdcBj5kY6PJLoviCiOr7Nskn/QZMf+huCU2ybxk6ml8kwUegldtBB+Fkp43OuJ8uCTM56ZzutI6xUvsNhLd0LzINYKrGiBfFv0h/9ILzHZAXdXOOd9ITwn+O0k+qjSaiz6MAMVXqIp1Z1ATskPantWbEylZDCJjtcXzZCKBk1Wj9sf63U3OXckMUlV0W1lFzYMfhbRBIz5uBeyCABdQxM2QtcHhgeECJ8GxEW+WW+alzJV5r37DccbmucSmrDZnkv+SjDfI085dWX2m7LDHr0WD/6Lu9w2B1+vzn3jtGYo/n8bP1Y+DCA/9R8mv2z77aKNnpKwA3q44Vi5fDm/7LbGQN/JpRmdEIs5oqizsm561fQWS8RxSemGZYOcWl60IrXKGDIGvFG7FgdDckAfhhiI39ar3UfwzUpdDxesM/5j3RXcvaLlHZ+q0wD00Ut8kSAXsXdEg3FgERUUWcjd9z3JBvexVIytifvv33zlr3QxZJDv81IHBe97JeKamSJIO+fwCezXqDnXuqCfkjqszv9K4CTEcXCOUvZrpLEGvn0YQukkVWRqZ1qt5BX7qzNKTFSPd367uR/bQKNSxIT8Yq3DqwWIPQ7zebRSl0h7p4s+HCrmE72AJMyDgWdgKurXZsAPQgueJo8ee9kkeTcEutDQfXnslckt8=
