language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: chalice deploy
notifications:
  slack:
    on_success: always
    on_failure: change
    template:
      - "%{repository}@%{branch} (%{commit}) - %{build_url}"
      - "Committed with: %{commit_message}"
      - "%{message}"
    rooms:
      secure: Re93pFZLxoHjhQzVIQysnUFmvybuCwZp3gNf5Dfwk6ZMIKYmZxeRVOc0DjUO9di11z01jEfVKUj/kf0higUVTIsNIIbYPdL2HULsv2LLuU4+/8T8wGjNk8Hltpe/C6tnXI4GxRgfAns3+/itjXYLeVpC/y8DbceLlFYSkVY35deuIb1BJzL9kS44QFBAO5C36zYX4YkaSvwN144lX737uDpj3a87xuI1ner9Rdn8wvQ9H7ne3WSWcldM7dB7beZ5Cadl2HcUfmpU8DaG5i/szCKHJl/Ce4fWWqJJrDDW8ISQ7ylf6REE5rnKEB/lPkPpCGACxupOZ+PaMzPkWYudCZzHU5kaO4sWpaOuqGaXkP1V3SovipW16q4PyNqolhzlI9HEhavquHQfSdES50v+72EUk7YQa+Z/GY14/eF2tr09OXCc3bL3Vf97pTTp3qBXUVyG3D2a56PcahQZYjQQ75ef9igXi0aWsVohCo3e9oMG6bPLhtgKzdo+rNl58g1ZkrLaQn7RFFolMDfaH3+GdHQnQ8IiyP7ojl2JFfqcFm32XstTGEOzlybMJjgtIyEC6FhJjzDHrxHJuJpT3gB+2PqQT0If64Ykcb2jissTCoUzCCrIjwU9D92vvc67cl5nPk3hvn8ZtJuIDDhrW++za/1B3jrRup2D8oQ+wf/T2Vk=
env:
  secure: dXELbxr31Mn4AdcBj5kY6PJLoviCiOr7Nskn/QZMf+huCU2ybxk6ml8kwUegldtBB+Fkp43OuJ8uCTM56ZzutI6xUvsNhLd0LzINYKrGiBfFv0h/9ILzHZAXdXOOd9ITwn+O0k+qjSaiz6MAMVXqIp1Z1ATskPantWbEylZDCJjtcXzZCKBk1Wj9sf63U3OXckMUlV0W1lFzYMfhbRBIz5uBeyCABdQxM2QtcHhgeECJ8GxEW+WW+alzJV5r37DccbmucSmrDZnkv+SjDfI085dWX2m7LDHr0WD/6Lu9w2B1+vzn3jtGYo/n8bP1Y+DCA/9R8mv2z77aKNnpKwA3q44Vi5fDm/7LbGQN/JpRmdEIs5oqizsm561fQWS8RxSemGZYOcWl60IrXKGDIGvFG7FgdDckAfhhiI39ar3UfwzUpdDxesM/5j3RXcvaLlHZ+q0wD00Ut8kSAXsXdEg3FgERUUWcjd9z3JBvexVIytifvv33zlr3QxZJDv81IHBe97JeKamSJIO+fwCezXqDnXuqCfkjqszv9K4CTEcXCOUvZrpLEGvn0YQukkVWRqZ1qt5BX7qzNKTFSPd367uR/bQKNSxIT8Yq3DqwWIPQ7zebRSl0h7p4s+HCrmE72AJMyDgWdgKurXZsAPQgueJo8ee9kkeTcEutDQfXnslckt8=
