language: python
python:
  - '2.7'
install: pip install -r requirements.txt
script: chalice deploy
env:
  secure: fll6KeDUXdsduOUkfFN6JFrw1Mstl3WQfCnLM1jx7JMV77DxuGbMwhocGA3/8xt8lal0870xrgMCSCJ8HtghIbxq7aYxiZ+yM8CPYGCGmd0p4yzBZhC//VTcpHZzuxmfX2stqL0O8PdWqm8N/BhmIUpWXjlrcGaAqy5H9g8+PotHvEbs9THh1LY0C1ou9oUQBkHYVl0ad8l21qaQYmCRwLllfatSn/ZZpVzygbmqJlYDuwgW6pkfY0OTRDUSwxXo86OKhbHemySwCKwcThnjB3WM1LZ68QA4X/gCLreJfAlXSuhBtMm6gLWsQieRQUvqmsBnA26l/gs7XoexVL/bYmx+f9LV9PzT3qncU6pK3twKzboI7pNEk8cx0vUj56cukeDQLUui5kCxnUvL3iQXYw6s844vQ7hHie0DiOV+dGJzd0ygdVl83OpQsL9Rph3e/PGwFjANlQ+eMbTROM0Mz6wwatULsmSMQzjo+BgNbUkpQ2nQM8PuqY+xY9rVe7CY8Op1PUHVI5OTlQ+sGGgs1GjPu9NAjGPBwfQyjsXZUSWKIpYXVwzEn9/GjyDYurzLwfRXwY/Iph35DxlurQqVvQDsOgBIHWsHsK7T2iJrJ++Gto0f28s+GM/18f0rG4Up99TJt4+LaacUXa0OTEHuLfZwnKrHSPRO9W0GMXwCmzM=
notifications:
  slack:
    on_success: always
    on_failure: change
    rooms:
      secure: AwwUP9dUuKtB4Xqv6JS8yj4yZH387Bb/AKHAO0qKRr6CiwNogw4GXFCpD7MQqEK5gc+nV9iG8EBwMEG3bHuKUI6v8bJlGXUZMpGltBm4zBiYdWTRgFigLmC4TWE2F5PyYZLmicebMnw2tAri5ufHyhdY0li10BOQSgci/abDDkyPOij0VMbGYKdC++IsVe/EYy4OqDMEKgE+HapZT33VHsJ8ckI2/Rwo8Beda99V5rF7G8sOgxBHbJ/ljvLgWpsh/rme+AdS2l9d0eJQv2NX6JvaIUfdB69pjNg6SEjULC7YsVkUQnSuTaH5hPWWvTQESr3JULZr1NtJzX20FYYMynLPmTfcGg0EE1XawJtxu+ulRGUux4Ps4MfK717nhVExIyrMq4Kgm1gNK+tXKpwmF/ISrpwu1GttgdufmY23yTvpbgJOnQ/YN9h7g1FJNAwn/vP7ukvk1w6fK0J6Sb2aZxzpmNZOau0Ni5vsjOXniMVPB5N0fLeyAQVO2gwkmEQQL/HF/a+maK+wfehvRjL6Z3cS3a/qg6S7QWxNok2bFsDgkFr01CZf7ywxIwomxZvNRP5iKpLo1Uu9+LYvGwM9Y06e38lutWuXvl6WT3/QkFwmlCzJsW9qHhnuyMF6m04zD48nH92LDm6BR0lwhH0LTXBU2N2TwQT5JVe8jt8iFmE=
