language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: chalice deploy
notifications:
  slack:
    on_success: always
    on_failure: change
    template:
    - "%{build_url}"
    - "%{commit_message}"
    - 'Change view: %{compare_url}'
    rooms:
      secure: dONFUJ9xQs5oZL/1x2vZ4Z1wP9GnP+HIXQ5736iYv0TfN+gLWgojGvrwIfRo7vsC4Jk36WKLPORFuijZIgj53xYaaP6bd2DOfiVpWb38IDvcMKxmX3DXF5zUHyXbId0TZsQ7sfHDYJjym5SWHwBFXhFB8zQpM9TY4+v4hc8EDvvIEYOgtrYLyfKiIOd9Azhf0f3etYvfq/yqUIocVOReo/FbIleO8n216RsiG+fSfGdTOoQgALR27q2dCNyCfMtTVdKfyI6YAZWsKXcEt8dt9G5IWL4Q+LnA72GEPrE2S90qqXUuyR1ONYOPiAp5nnfewtm4ConMc0lm4OfXQm6rbFmwlGZ9YirjWbo4vsZm+nTlm9vAFC8c0pPkDr5gcV8WsHoRbAXA+kwPl3cfT5oy9QWQGnhpSUeSF3ZhXaLu3jObq3OL1nGImAqLnNVjqBKYFLdQ+Laa2G2hyscubvMrD+CbAEcvcTXjefH6//OmWREoMoQW4mrP/Q2pBRItLaKFQTViFqCai+Lf8Yui80yoTQgYET9/euIk7BS4z8M8Y7iIeN2ilc1vmA3lOzd1vmJmshlgHsKrshcVhwBGOhbgRzkboEu5FP4yk7J3hALxl3BVD/ceSXRrvkSuCkfE5+IPeZf75AOUdq7IhlHJmrZ6MHYgk6p5c9kOdrI1hNLIoWM=
env:
  secure: dXELbxr31Mn4AdcBj5kY6PJLoviCiOr7Nskn/QZMf+huCU2ybxk6ml8kwUegldtBB+Fkp43OuJ8uCTM56ZzutI6xUvsNhLd0LzINYKrGiBfFv0h/9ILzHZAXdXOOd9ITwn+O0k+qjSaiz6MAMVXqIp1Z1ATskPantWbEylZDCJjtcXzZCKBk1Wj9sf63U3OXckMUlV0W1lFzYMfhbRBIz5uBeyCABdQxM2QtcHhgeECJ8GxEW+WW+alzJV5r37DccbmucSmrDZnkv+SjDfI085dWX2m7LDHr0WD/6Lu9w2B1+vzn3jtGYo/n8bP1Y+DCA/9R8mv2z77aKNnpKwA3q44Vi5fDm/7LbGQN/JpRmdEIs5oqizsm561fQWS8RxSemGZYOcWl60IrXKGDIGvFG7FgdDckAfhhiI39ar3UfwzUpdDxesM/5j3RXcvaLlHZ+q0wD00Ut8kSAXsXdEg3FgERUUWcjd9z3JBvexVIytifvv33zlr3QxZJDv81IHBe97JeKamSJIO+fwCezXqDnXuqCfkjqszv9K4CTEcXCOUvZrpLEGvn0YQukkVWRqZ1qt5BX7qzNKTFSPd367uR/bQKNSxIT8Yq3DqwWIPQ7zebRSl0h7p4s+HCrmE72AJMyDgWdgKurXZsAPQgueJo8ee9kkeTcEutDQfXnslckt8=
